services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: kvack
      POSTGRES_PASSWORD: mojegeslo
      POSTGRES_DB: kvackalnica
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kvack -d kvackalnica"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend_kvackalnica
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgres://kvack:mojegeslo@db:5432/kvackalnica"
      PORT: 5000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend_kvackalnica:/app
      - /app/node_modules
      - ./backend_kvackalnica/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend_kvackalnica
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend_kvackalnica:/app:cached
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=5173
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: